# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckImage',
            fields=[
                ('image_id', models.CharField(help_text='图片Id', max_length=255, primary_key=True, serialize=False)),
                ('image_value', models.CharField(help_text='图片值', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikename', models.CharField(blank=True, default='', help_text='别名', max_length=255, null=True)),
                ('mobile_no', models.CharField(help_text='手机号', max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('man', '男性'), ('woman', '女性'), ('other', '其他'), ('privacy', '隐私')], default='privacy', help_text='性别', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
