# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mirr_accounts', '0003_auto_20170221_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('man', '男性'), ('woman', '女性'), ('other', '其他'), ('privacy', '隐私')], default='privacy', help_text='性别', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_no',
            field=models.CharField(blank=True, help_text='手机号', max_length=255, null=True),
        ),
    ]
